-- Enterprise Reporting System - Oracle Database Schema
-- Execute this script in your Oracle database as a privileged user

-- Create tablespace for the application (optional but recommended)
CREATE TABLESPACE ENTERPRISE_REPORTS
DATAFILE 'enterprise_reports.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G;

-- Create application user
CREATE USER ENTERPRISE_USER IDENTIFIED BY "EnterprisePass123!"
DEFAULT TABLESPACE ENTERPRISE_REPORTS
TEMPORARY TABLESPACE TEMP;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO ENTERPRISE_USER;
GRANT CREATE VIEW TO ENTERPRISE_USER;
GRANT CREATE PROCEDURE TO ENTERPRISE_USER;
GRANT CREATE TRIGGER TO ENTERPRISE_USER;
GRANT CREATE SEQUENCE TO ENTERPRISE_USER;
GRANT UNLIMITED TABLESPACE TO ENTERPRISE_USER;

-- Connect as ENTERPRISE_USER for the rest of the script
-- ALTER SESSION SET CURRENT_SCHEMA = ENTERPRISE_USER;

-- Users table
CREATE TABLE USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'user' CHECK (ROLE IN ('admin', 'user')),
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(50)
);

-- Auto Mail Reports table
CREATE TABLE AUTO_MAIL_REPORTS (
    REPORT_ID VARCHAR2(50) PRIMARY KEY,
    REPORT_NAME VARCHAR2(255) NOT NULL,
    MAIL_FROM VARCHAR2(255) NOT NULL,
    MAIL_TO CLOB NOT NULL, -- JSON array of email addresses
    MAIL_SUBJECT VARCHAR2(500) NOT NULL,
    MAIL_BODY CLOB NOT NULL,
    QUERY_TEXT CLOB NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    SCHEDULE_TYPE VARCHAR2(50), -- Daily, Weekly, Monthly, Quarterly
    SCHEDULE_TIME VARCHAR2(10), -- HH:MM format
    LAST_RUN TIMESTAMP,
    NEXT_RUN TIMESTAMP,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AUTO_MAIL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

-- Instant Reports table
CREATE TABLE INSTANT_REPORTS (
    REPORT_ID VARCHAR2(50) PRIMARY KEY,
    REPORT_NAME VARCHAR2(255) NOT NULL,
    QUERY_TEXT CLOB NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INSTANT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

-- Master Upload Configurations table
CREATE TABLE MASTER_UPLOADS (
    UPLOAD_ID VARCHAR2(50) PRIMARY KEY,
    UPLOAD_NAME VARCHAR2(255) NOT NULL,
    TABLE_NAME VARCHAR2(128) NOT NULL,
    COLUMN_MAPPING CLOB NOT NULL, -- JSON object mapping Excel columns to DB columns
    VALIDATION_RULES CLOB, -- JSON array of validation rules
    SAMPLE_FILE_PATH VARCHAR2(500),
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

-- User Access Rights table
CREATE TABLE USER_ACCESS_RIGHTS (
    ACCESS_ID VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    RESOURCE_TYPE VARCHAR2(50) NOT NULL, -- 'auto_mail', 'instant_report', 'master_upload'
    RESOURCE_ID VARCHAR2(50) NOT NULL,
    ACCESS_LEVEL VARCHAR2(20) DEFAULT 'read' CHECK (ACCESS_LEVEL IN ('read', 'write', 'execute')),
    GRANTED_BY VARCHAR2(50) NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCESS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_ACCESS_GRANTED_BY FOREIGN KEY (GRANTED_BY) REFERENCES USERS(USER_ID),
    CONSTRAINT UK_USER_RESOURCE UNIQUE (USER_ID, RESOURCE_TYPE, RESOURCE_ID)
);

-- Query Executions table (for tracking instant report runs)
CREATE TABLE QUERY_EXECUTIONS (
    EXECUTION_ID VARCHAR2(50) PRIMARY KEY,
    REPORT_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'running' CHECK (STATUS IN ('running', 'completed', 'failed', 'cancelled')),
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    END_TIME TIMESTAMP,
    ERROR_MESSAGE CLOB,
    RESULT_FILE_PATH VARCHAR2(500),
    PARAMETERS CLOB, -- JSON object with query parameters
    CONSTRAINT FK_EXEC_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES INSTANT_REPORTS(REPORT_ID),
    CONSTRAINT FK_EXEC_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Email Logs table
CREATE TABLE EMAIL_LOGS (
    LOG_ID VARCHAR2(50) PRIMARY KEY,
    REPORT_ID VARCHAR2(50),
    REPORT_TYPE VARCHAR2(50) NOT NULL, -- 'auto_mail', 'instant_report'
    RECIPIENT_EMAIL VARCHAR2(255) NOT NULL,
    SUBJECT VARCHAR2(500) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'pending' CHECK (STATUS IN ('pending', 'sent', 'failed')),
    ERROR_MESSAGE CLOB,
    SENT_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Upload Logs table
CREATE TABLE UPLOAD_LOGS (
    LOG_ID VARCHAR2(50) PRIMARY KEY,
    UPLOAD_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    TOTAL_ROWS NUMBER DEFAULT 0,
    SUCCESS_ROWS NUMBER DEFAULT 0,
    ERROR_ROWS NUMBER DEFAULT 0,
    STATUS VARCHAR2(20) DEFAULT 'processing' CHECK (STATUS IN ('processing', 'completed', 'failed')),
    ERROR_DETAILS CLOB,
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    CONSTRAINT FK_UPLOAD_LOG_UPLOAD_ID FOREIGN KEY (UPLOAD_ID) REFERENCES MASTER_UPLOADS(UPLOAD_ID),
    CONSTRAINT FK_UPLOAD_LOG_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create sequences for ID generation
CREATE SEQUENCE SEQ_USER_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPORT_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_UPLOAD_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACCESS_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXECUTION_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOG_ID START WITH 1000 INCREMENT BY 1;

-- Create indexes for better performance
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_AUTO_MAIL_ACTIVE ON AUTO_MAIL_REPORTS(IS_ACTIVE);
CREATE INDEX IDX_AUTO_MAIL_NEXT_RUN ON AUTO_MAIL_REPORTS(NEXT_RUN);
CREATE INDEX IDX_INSTANT_ACTIVE ON INSTANT_REPORTS(IS_ACTIVE);
CREATE INDEX IDX_ACCESS_USER_ID ON USER_ACCESS_RIGHTS(USER_ID);
CREATE INDEX IDX_ACCESS_RESOURCE ON USER_ACCESS_RIGHTS(RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_EXEC_STATUS ON QUERY_EXECUTIONS(STATUS);
CREATE INDEX IDX_EXEC_USER_ID ON QUERY_EXECUTIONS(USER_ID);
CREATE INDEX IDX_EMAIL_STATUS ON EMAIL_LOGS(STATUS);
CREATE INDEX IDX_UPLOAD_STATUS ON UPLOAD_LOGS(STATUS);

-- Insert default admin user (password: admin123)
INSERT INTO USERS (
    USER_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE, IS_ACTIVE
) VALUES (
    'USR1000', 'admin', 'admin@company.com', 
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- bcrypt hash for 'admin123'
    'System', 'Administrator', 'admin', 1
);

-- Insert sample user (password: user123)
INSERT INTO USERS (
    USER_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE, IS_ACTIVE
) VALUES (
    'USR1001', 'user', 'user@company.com', 
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- bcrypt hash for 'user123'
    'Regular', 'User', 'user', 1
);

COMMIT;